services:
  mariadb:
    image: mariadb:10-ubi
    container_name: linda_admin_mariaDB
    ports:
      - $DB_PORT:$DB_PORT
    networks:
      - linda_admin_network
    env_file: ".env"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: linda_admin_phpmyadmin
    env_file:
      - path: ".env"
        required: true
    ports:
      - "8090:80"
    networks:
      - linda_admin_network
    environment:
      PMA_HOST: mariadb
      PMA_CONTROLPORT: $DB_PORT
    depends_on:
      - mariadb

  frontend:
    build: ./
    ports:
      - "8000:8000"
    command: /bin/bash
    container_name: linda_admin_frontend
    env_file: ".env"
    environment:
      - DB_HOST=172.28.5.254 # Fixes issues on Windows...
    volumes:
      - website_volume:/website
    networks:
      - linda_admin_network
    working_dir: /website
    stdin_open: true
    tty: true
    depends_on:
      - mariadb
      - phpmyadmin

volumes:
  website_volume:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}
      o: bind

networks:
  linda_admin_network:
    ipam:
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.5.0/24
          gateway: 172.28.5.254 # Fixes issues on Windows...