services:
  mariadb:
    image: mariadb:10-ubi
    container_name: linda_admin_mariaDB
    env_file: ".env"
    ports:
      - $DB_PORT:$DB_PORT
    networks:
      - proxy-network
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: linda_admin_phpmyadmin
    env_file:
      - path: ".env"
        required: true
    ports:
      - "8090:80"
    networks:
      - proxy-network
    environment:
      PMA_HOST: mariadb
      PMA_CONTROLPORT: $DB_PORT
    depends_on:
      - mariadb

  frontend:
    build: ./
    ports:
      - "8000:8000"
    networks:
      - proxy-network
    container_name: linda_admin_frontend
    env_file: ".env"
    command: /bin/bash ./entrypoint.sh
    volumes:
      - website_volume:/website
    working_dir: /website
    stdin_open: true
    tty: true
    depends_on:
      - mariadb
      - phpmyadmin

volumes:
  website_volume:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}
      o: bind

networks:
  proxy-network:
    name: custom_network
